# Consuming Customer Specific Datasets from Data Sharing Partners using BigQuery
# 30 minutes
# 1 Credit
# GSP1043
# Google Cloud self-paced labs logo

# Overview
# A common scenario is where a Google Cloud Data Sharing Partner has proprietary datasets that customers can use for their analytics use cases. Customers need to subscribe to this data, query it within their own platform, then augment it with their own datasets and use their visualization tools for their customer facing dashboards. This enables Data Sharing Partners to simplify and accelerate how they build and deliver value from data-driven solutions.

# overview diagram

# Through integration with Google Cloud IAM, you can set permissions on BigQuery objects to enable access by users inside or outside of organizations. In this lab, you will learn how Data Sharing Partners create Data Twins for customers either on Google Cloud or a different cloud service provider. For the purposes of this lab, the customer is on Google Cloud in a different project.

# In this lab you will wear two hats and be provided with three Google Cloud projects. In the first project, you are taking on the role of a Data Sharing Partner sharing a dataset generated by the partner's hosted solution using a Data Publishing project. In the second project, you will assume the role of a Data Sharing Partner who will share the source dataset in partner project as an authorized view in the Data Publishing project. In the third project, you will assume the role of a customer who will access the authorized view into their project as a Data Twin and join the data with their solution dataset to create enriched datasets.

# Objectives
# In this lab, you will:

# Create an authorized view for a Data Sharing Partner Dataset in different projects

# Secure access to the authorized view for a specific customer

# Use a customer generated dataset to join with the Data Sharing Partner dataset to create new insights

# Setup and Requirements
# Before you click the Start Lab button
# Read these instructions. Labs are timed and you cannot pause them. The timer, which starts when you click Start Lab, shows how long Google Cloud resources will be made available to you.

# This hands-on lab lets you do the lab activities yourself in a real cloud environment, not in a simulation or demo environment. It does so by giving you new, temporary credentials that you use to sign in and access Google Cloud for the duration of the lab.

# To complete this lab, you need:

# Access to a standard internet browser (Chrome browser recommended).
# Note: Use an Incognito or private browser window to run this lab. This prevents any conflicts between your personal account and the Student account, which may cause extra charges incurred to your personal account.
# Time to complete the lab---remember, once you start, you cannot pause a lab.
# Note: If you already have your own personal Google Cloud account or project, do not use it for this lab to avoid extra charges to your account.
# How to start your lab and sign in to the Google Cloud Console
# Click the Start Lab button. If you need to pay for the lab, a pop-up opens for you to select your payment method. On the left is the Lab Details panel with the following:

# The Open Google Console button
# Time remaining
# The temporary credentials that you must use for this lab
# Other information, if needed, to step through this lab
# Click Open Google Console. The lab spins up resources, and then opens another tab that shows the Sign in page.

# Tip: Arrange the tabs in separate windows, side-by-side.

# Note: If you see the Choose an account dialog, click Use Another Account.
# If necessary, copy the Username from the Lab Details panel and paste it into the Sign in dialog. Click Next.

# Copy the Password from the Lab Details panel and paste it into the Welcome dialog. Click Next.

# Important: You must use the credentials from the left panel. Do not use your Google Cloud Skills Boost credentials.
# Note: Using your own Google Cloud account for this lab may incur extra charges.
# Click through the subsequent pages:

# Accept the terms and conditions.
# Do not add recovery options or two-factor authentication (because this is a temporary account).
# Do not sign up for free trials.
# After a few moments, the Cloud Console opens in this tab.

# Note: You can view the menu with a list of Google Cloud Products and Services by clicking the Navigation menu at the top-left. Navigation menu icon
# Created an authorized table
# In the first project, you will take on the role of a Data Sharing Partner creating and sharing a dataset using an authorized table.

# Create the Customer Authorized Table
# From the lab pane. open the Data Sharing Partner Project Console and log in with the associated credentials.

# From the Navigation Menu, go to BigQuery > SQL Workspace.

# Run the following query to create a source dataset by selecting the top 10 cities of each state sorted by land area:

# SELECT * FROM (
# SELECT *, ROW_NUMBER() OVER (PARTITION BY state_code ORDER BY area_land_meters DESC) AS cities_by_area
# FROM `bigquery-public-data.geo_us_boundaries.zip_codes`) cities
# WHERE cities_by_area <= 10 ORDER BY cities.state_code
# LIMIT 1000;
# Copied!
# From the toolbar, click More > Query Settings.

# Select the Set a destination table for query results option.

# For the Dataset select Data Sharing Partner Project ID.demo_dataset.

# For Table ID type authorized_table.

# Leave the rest of the fields as default and click Save.

# Click Run to run the query again to write the results to the table you specified.

# Verify the authorized_table has been created.

# Authorize the dataset
# From the BigQuery Explorer pane, open the demo_dataset and click + Sharing > Authorize dataset.

# Add the authorized view that needs to be authorized to share: Data Sharing Partner Project ID.demo_dataset.

# Click Add Authorization.

# Click Close.

# Grant permissions to the Data Publisher to access the view
# Under your project, inside of demo_dataset, open authorized_table.

# Click Share.

# Click on Add Principal and add the Data Publisher and Customer users:

# Data Publisher username
# Customer username
# Select the BigQuery Data Viewer role.

# add bigquery data viewer principal

# Click Save.
# Click Check my progress to verify your performed task.

# Created an Authorized Table
# Create an authorized view in the Data Publishing project
# In the second project, you will assume the role of a Data Sharing Partner who will share the source dataset in partner project as an authorized view in the Data Publishing project.

# Close the Data Sharing Partner Project Console and from the lab pane open the Data Publisher Project Console. Log in with the associated credentials.

# From the Navigation Menu, go to BigQuery > SQL Workspace.

# Run the following query to select cities in New York state from the authorized view:

# SELECT *
# FROM `Data Sharing Partner Project ID.demo_dataset.authorized_table`
# WHERE state_code="NY"
# LIMIT 1000
# Copied!
# On the query toolbar, select Save > Save View.

# Click in the Dataset field and select data_publisher_dataset.

# In the Table field, type authorized_view.

# Click Save. You should now be able to see the dataset and table, as well as query it.

# Assign IAM permissions to the Data Publisher view
# From the BigQuery Explorer pane, open the data_publisher_dataset and click + Sharing > Authorize Views.

# Add the authorized view that needs to be authorized to share: Data Publisher Project ID.data_publisher_dataset.authorized_view.

# Click Add Authorization.

# Click Close.

# Grant permissions to the customer to access the view
# Under your project, inside of data_publisher_dataset, open authorized_view.

# Click Share.

# Click on Add Principal and add the Customer user:

# Data Twin username
# Select the BigQuery Data Viewer role.

# add bigquery data viewer principal

# Click Save.
# Click Check my progress to verify your performed task.

# Create an authorized view in the Data Publishing project
# Access the authorized view as a Data Twin
# In the third project, the student will assume the role of a customer who will access the authorized view into their project as a Data Twin and join the data with their solution dataset to create enriched datasets.

# Close the Data Publisher Console and from the lab pane open the Customer (Data Twin) Project Console. Log in with the associated credentials.

# From the Navigation Menu, go to BigQuery > SQL Workspace.

# Execute the following query to access data from the Data Sharing Partner Data publishing project and join the Customer’s data and partner's view to create new insights.

# SELECT cities.zip_code, cities.city, cities.state_code, customers.last_name, customers.first_name
# FROM `Data Twin Project ID.customer_dataset.customer_info` as customers
# JOIN `Data Publisher Project ID.data_publisher_dataset.authorized_view` as cities
# ON cities.state_code = customers.state;
# Copied!
# Your results should resemble the following:

# customer query

# On the query toolbar, select Save > Save View.

# Click in the Dataset field and select customer_dataset.

# In the Table field, type customer_table.

# Click Save. You should now be able to see the dataset and table, as well as query it.

# Click Check my progress to verify your performed task.

# Access the authorized view as a Data Twin
# Confirm functionality of the Customer (Data Twin)
# To confirm the functionality of the Data Twin, you will insert a new row in the Data Sharing Partner Project and test the functionality inside of the customer project.

# Close the Customer (Data Twin) Project Console and from the lab pane open the Data Sharing Partner Project Console. Log in with the associated credentials.

# From the Navigation Menu, go to BigQuery > SQL Workspace.

# Run the following query to insert a new row in the Data Sharing Partner dataset:

# INSERT INTO
#  `Data Sharing Partner Project ID.demo_dataset.authorized_table` (zip_code,
#    city,
#    county,
#    state_fips_code,
#    state_code,
#    state_name,
#    fips_class_code,
#    mtfcc_feature_class_code,
#    functional_status,
#    area_land_meters,
#    area_water_meters,
#    cities_by_area)
# VALUES
#  ("11012", "New City", "New County", "02", "NY", "New York", "B5", "G6350", "S", 123632007174.0, 544474039.0, 10)
# Copied!
# You should see the following output

# This statement added 1 row to authorized_table.
# Close the Data Sharing Partner Project Console and from the lab pane open the Customer (Data Twin) Project Console. Log in with the associated credentials.

# Finally, query the view in Customer (Data Twin) project to confirm the newly added row is visible.

# SELECT cities.zip_code, cities.city, cities.state_code, customers.last_name, customers.first_name
# FROM `Data Twin Project ID.customer_dataset.customer_info` as customers
# JOIN `Data Publisher Project ID.data_publisher_dataset.authorized_view` as cities
# ON cities.state_code = customers.state;
# Copied!
# You results should resemble the following:

# final results updated row

# Congratulations!
# In this lab, you created an authorized view for an Data Sharing Partner dataset to share with a user in a Data Publishing project. You then logged into the Data Publishing project and shared the authorized view with a customer user in a Data Twin project. Lastly, you logged into the Customer/Data Twin project and joined the data with customer specific data to create an enriched dataset.

# Google Cloud training and certification
# ...helps you make the most of Google Cloud technologies. Our classes include technical skills and best practices to help you get up to speed quickly and continue your learning journey. We offer fundamental to advanced level training, with on-demand, live, and virtual options to suit your busy schedule. Certifications help you validate and prove your skill and expertise in Google Cloud technologies.

# Manual Last Updated: September 27, 2022
# Lab Last Tested: February 01, 2023
# Copyright 2023 Google LLC All rights reserved. Google and the Google logo are trademarks of Google LLC. All other company and product names may be trademarks of the respective companies with which they are associated.